apiVersion: v1
kind: Service
metadata:
  name: summarizer
  labels:
    app: summarizer
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: summarizer
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer
  labels:
    app: summarizer
spec:
  selector:
    matchLabels:
      app: summarizer
  template:
    metadata:
      labels:
        app: summarizer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: summarizer
          image: "ko://github.com/lofifnc/cruncher/machinelearningteam/summary-statistics-service/cmd/service"
          args: []
          env:
            - name: "SERVER_ADDR"
              value: "summarizer-backend:50051"
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: 256Mi
              cpu: 1000m
            limits:
              memory: 768Mi
              cpu: 1000m
#          We would have to include https://github.com/grpc-ecosystem/grpc-health-probe for this to work. Maybe later.
#          readinessProbe:
#            exec:
#              command:
#                ["/bin/grpc-health-probe", "-addr=:50051"]
#          livenessProbe:
#            exec:
#              command:
#                ["/bin/grpc-health-probe", "-addr=:50051"]
