apiVersion: v1
kind: Service
metadata:
  name: summarizer-backend
  labels:
    app: summarizer-backend
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: summarizer-backend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-backend
  labels:
    app: summarizer-backend
spec:
  selector:
    matchLabels:
      app: summarizer-backend
  template:
    metadata:
      labels:
        app: summarizer-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: summarizer-backend
          image: "docker.io/lofifnc/summarizer-backend"
          imagePullPolicy: Always
          args: []
          env:
            - name: PORT
              value: "50051"
          ports:
            - name: grpc
              containerPort: 50051
            - name: prometheus
              containerPort: 5001
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 768Mi
              cpu: 500m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: summarizer-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: summarizer-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
